spring:
  datasource:
    url: jdbc:mysql://localhost:3306/note_and_read?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#    &useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:mariadb://wsl.lan:3306/note_and_read #?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: wsl.lan
    port: 6379
    lettuce:
      pool:
        max-wait: -1
        max-idle: 8
        max-active: 8
        min-idle: 0
    connect-timeout: 2000ms

server:
  port: 19201
  address: 0.0.0.0

#  servlet:
#    session:
#      cookie:
#        domain: note.com

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: me.deamonet.nar.entity
  configuration:
    map-underscore-to-camel-case: true
